#pragma once

namespace Quartz
{
#ifndef QUARTZ_LOG_LEVEL_ENUM

	enum LogLevel
	{
		LOG_LEVEL_TRACE,
		LOG_LEVEL_DEBUG,
		LOG_LEVEL_INFO,
		LOG_LEVEL_WARNING,
		LOG_LEVEL_ERROR,
		LOG_LEVEL_FATAL
	};

#define QUARTZ_LOG_LEVEL_ENUM

#endif

	enum LogColor
	{
		LOG_COLOR_DEFAULT,
		LOG_COLOR_BLACK,
		LOG_COLOR_DARK_BLUE,
		LOG_COLOR_DARK_GREEN,
		LOG_COLOR_DARK_CYAN,
		LOG_COLOR_DARK_RED,
		LOG_COLOR_DARK_MAGENTA,
		LOG_COLOR_DARK_YELLOW,
		LOG_COLOR_DARK_GRAY,
		LOG_COLOR_GRAY,
		LOG_COLOR_BLUE,
		LOG_COLOR_GREEN,
		LOG_COLOR_CYAN,
		LOG_COLOR_RED,
		LOG_COLOR_MAGENTA,
		LOG_COLOR_YELLOW,
		LOG_COLOR_WHITE
	};
}